version: '3'

services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snipeit
    ports:
    - "8000:80"
    volumes:
    # - ./logs:/var/www/html/storage/logs
    - ./snipeit_data:/var/lib/snipeit
    - ./snipeit_logs/apache2:/var/log/apache2
    depends_on:
    - mariadb
    env_file:
    - env.test
    networks:
    - snipeit-backend

  mariadb:
    image: mariadb:10.6.4-focal
    volumes:
    - db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: snipeit
      MARIADB_DATABASE: snipeit
      MARIADB_USER: snipeit
      MARIADB_PASSWORD: snipeit
    networks:
    - snipeit-backend
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.5-buster
    networks:
    - snipeit-backend

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
    # - 1025:1025
    - "8025:8025"
    networks:
    - snipeit-backend

  caddy:
    image: caddy:2.6.2-alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
    ports:
      - 80:80
      - 443:443
    networks:
      - snipeit-backend
    depends_on:
      - snipeit

volumes:
  db: {}

networks:
  snipeit-backend: {}
